version: 2

defaults: &defaults
  working_directory: ~/stories-facets
  docker:
    - image: circleci/node:8.9.1

jobs:
  build:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-npm-deps-{{ checksum "package-lock.json" }}
      
      - run: npm install
      
      - save_cache:
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

      - run: ./node_modules/.bin/gulp deploy

      - persist_to_workspace:
          root: ~/stories-facets
          paths: .
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/stories-facets
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/stories-facets/.npmrc
      - run:
          name: Publish package
          command: npm publish --access public

workflows:
  version: 2
  publish:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
